#!/bin/bash
# Unikernel Linux
# Copyright (C) 2018-2022 Red Hat Inc., Boston University,
# Ali Raza, Tommy Unger, Eric Munson, Richard W.M. Jones.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

# This is the init script that runs inside the unikernel when it first
# boots.

mount -t proc none /proc
mount -t sysfs none /sys
#mount -t debugfs none /sys/kernel/debug/

#echo deleting then creating mytmpfs
rm -rf mytmpfs
mkdir /mytmpfs
mount -t tmpfs -o size=4g tmpfs /mytmpfs

#echo Pinning virt queues to cores
./set_irq_affinity_virtio.sh

#/sbin/ip addr add 10.0.2.15 dev eth0
#/sbin/ip link set dev eth0 up

exec /bin/bash

