extern int printf(const char *fmt, ...);
int __dladdr(){printf("function %s NYI\n","__dladdr"); while(1);}
int __dladdr1(){printf("function %s NYI\n","__dladdr1"); while(1);}
int __dlclose(){printf("function %s NYI\n","__dlclose"); while(1);}
int __dlerror(){printf("function %s NYI\n","__dlerror"); while(1);}
int __dlinfo(){printf("function %s NYI\n","__dlinfo"); while(1);}
int __dlmopen(){printf("function %s NYI\n","__dlmopen"); while(1);}
int __dlopen(){printf("function %s NYI\n","__dlopen"); while(1);}
int __dlsym(){printf("function %s NYI\n","__dlsym"); while(1);}
int __dlvsym(){printf("function %s NYI\n","__dlvsym"); while(1);}
int __libc_register_dlfcn_hook(){printf("function %s NYI\n","__libc_register_dlfcn_hook"); while(1);}
int bp_ftruncate64(){printf("function %s NYI\n","ukl_bp_ftruncate64"); while(1);}
int bp_clock_getres_time64(){printf("function %s NYI\n","ukl_bp_clock_getres_time64"); while(1);}
int bp_clock_gettime64(){printf("function %s NYI\n","ukl_bp_clock_gettime64"); while(1);}
int bp_fcntl64(){printf("function %s NYI\n","ukl_bp_fcntl64"); while(1);}
int bp_ppoll_time64(){printf("function %s NYI\n","ukl_bp_ppoll_time64"); while(1);}
int bp_utimensat_time64(){printf("function %s NYI\n","ukl_bp_utimensat_time64"); while(1);}
int bp_preadv64(){printf("function %s NYI\n","ukl_bp_preadv64"); while(1);}
int bp_pwritev64(){printf("function %s NYI\n","ukl_bp_pwritev64"); while(1);}
int bp_preadv64v2(){printf("function %s NYI\n","ukl_bp_preadv64v2"); while(1);}
int bp_pwritev64v2(){printf("function %s NYI\n","ukl_bp_pwritev64v2"); while(1);}
int bp_truncate64(){printf("function %s NYI\n","ukl_bp_truncate64"); while(1);}
int bp__sysctl(){printf("function %s NYI\n","ukl_bp__sysctl"); while(1);}
int bp_clock_settime64(){printf("function %s NYI\n","ukl_bp_clock_settime64"); while(1);}
//int __pthread_unwind(){printf("function %s NYI\n","__pthread_unwind"); while(1);}
