int printf(char *fmt, ...);
int ukl_bp_timerfd_settime64(){printf("function %s NYI\n","ukl_bp_timerfd_settime64"); while(1);}
int ukl_bp_utimensat_time64(){printf("function %s NYI\n","ukl_bp_utimensat_time64"); while(1);}
int ukl_bp_pselect6_time64(){printf("function %s NYI\n","ukl_bp_pselect6_time64"); while(1);}
int ukl_bp_map_shadow_stack(){printf("function %s NYI\n","ukl_bp_map_shadow_stack"); while(1);}
int ukl_bp_rt_sigtimedwait_time64(){printf("function %s NYI\n","ukl_bp_rt_sigtimedwait_time64"); while(1);}
int ukl_bp_recvmmsg_time64(){printf("function %s NYI\n","ukl_bp_recvmmsg_time64"); while(1);}
int ukl_bp_truncate64(){printf("function %s NYI\n","ukl_bp_truncate64"); while(1);}
int ukl_bp_fchmodat2(){printf("function %s NYI\n","ukl_bp_fchmodat2"); while(1);}
int ukl_bp_clock_getres_time64(){printf("function %s NYI\n","ukl_bp_clock_getres_time64"); while(1);}
int ukl_bp_clock_adjtime64(){printf("function %s NYI\n","ukl_bp_clock_adjtime64"); while(1);}
int ukl_bp_mq_timedreceive_time64(){printf("function %s NYI\n","ukl_bp_mq_timedreceive_time64"); while(1);}
int ukl_bp_futex_time64(){printf("function %s NYI\n","ukl_bp_futex_time64"); while(1);}
int ukl_bp_clock_nanosleep_time64(){printf("function %s NYI\n","ukl_bp_clock_nanosleep_time64"); while(1);}
int ukl_bp_sched_rr_get_interval_time64(){printf("function %s NYI\n","ukl_bp_sched_rr_get_interval_time64"); while(1);}
int ukl_bp_ftruncate64(){printf("function %s NYI\n","ukl_bp_ftruncate64"); while(1);}
int ukl_bp_mq_timedsend_time64(){printf("function %s NYI\n","ukl_bp_mq_timedsend_time64"); while(1);}
int ukl_bp_ppoll_time64(){printf("function %s NYI\n","ukl_bp_ppoll_time64"); while(1);}
int ukl_bp_timerfd_gettime64(){printf("function %s NYI\n","ukl_bp_timerfd_gettime64"); while(1);}
int ukl_bp_clock_gettime64(){printf("function %s NYI\n","ukl_bp_clock_gettime64"); while(1);}
int ukl_bp_clock_settime64(){printf("function %s NYI\n","ukl_bp_clock_settime64"); while(1);}
int ukl_bp_umount2(){printf("function %s NYI\n","ukl_bp_umount2"); while(1);}
